seed: 1337

num_workers: 16
batch_size: 128

dataset: "patentfigurevqa"

aspects:
  - "type"
  - "uspc"
  - "projection"
  - "object"
options_count:
  - 5
  - 10
  - 20
models:
  - "rn50"
  - "rx101"
  - "flant5xl_zs_all_tasks"
  - "flant5xl_fs_{}_all_tasks_{}"

cls_dataset_path: "dataset/classification"
raw_dataset_path: "dataset/raw_dataset"
